In [36]:
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [37]:
import glob,os
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.problems import *
from pymoo.optimize import minimize
from pymoo.visualization.scatter import Scatter

In [38]:
request_count = [10,20,30]
tasks = []
for file in glob.glob(os.path.join('./pymoo/problems/nfv/sfc/data/input', '*_network.txt')):
    if 'nsf' not in file:
        continue
    n = file_to_network(file)
    # requests = file_to_requests(os.path.join(args.input, f'{dat}_requests.txt'))
    for cnt in request_count:
        req_file = file.replace('network', f'{cnt}requests')
        name = req_file.split('\\')[-1][:-5]
        requests = file_to_requests(req_file)
        name = req_file.split('\\')[-1][:-5]
        tasks.append((n,requests,name))


In [40]:
import numpy as np
rs = []
for i in range(len(tasks)):
    problem = get_problem("nfv_gp",tasks[i][0],tasks[i][1],tasks[i][2])
    algorithm = NSGA2(pop_size=100)
    res = minimize(problem,
                algorithm,
                ('n_gen', 50),
                seed=1,
                verbose=True)
    rs.append(res)
    X, F = res.opt.get("X", "F")
    # np.savetxt(f'result/nsga2/{tasks[i][2]}.txt',np.array(F))
    break

n_gen  |  n_eval  | n_nds  |      igd      |       gd      |       hv     
     1 |      100 |     11 |  0.3551531357 |  0.3100242371 |  0.2213333333
     2 |      200 |     15 |  0.3525422793 |  0.2931028985 |  0.2240000000
     3 |      300 |     21 |  0.3525422793 |  0.2964178626 |  0.2240000000
     4 |      400 |     30 |  0.3525422793 |  0.2951478178 |  0.2240000000
     5 |      500 |     38 |  0.3493567490 |  0.2866788226 |  0.2293333333
     6 |      600 |     44 |  0.3464193996 |  0.2853549665 |  0.2336666667
     7 |      700 |     62 |  0.3464193996 |  0.2855827793 |  0.2336666667
     8 |      800 |     76 |  0.3464193996 |  0.2851854390 |  0.2336666667
     9 |      900 |    100 |  0.3464193996 |  0.2853544600 |  0.2336666667
    10 |     1000 |    100 |  0.3464193996 |  0.2855549678 |  0.2336666667
    11 |     1100 |    100 |  0.3720121925 |  0.2848809270 |  0.2043333333
    12 |     1200 |    100 |  0.3720121925 |  0.2852408714 |  0.2043333333
    13 |     1300 |    10

In [41]:
F

array([[0.5       , 0.70666667],
       [0.8       , 0.44333333],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.8       , 0.44333333],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.8       , 0.44333333],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.8       , 0.44333333],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.7       , 0.48666667],
       [0.6       , 0.58333333],
       [0.

In [ ]:
import numpy as np
x = np.arange(5)
y = np.arange(4)
np.random.choice(np.concatenate((x,y)),4)

array([3, 1, 2, 0])

In [ ]:
u = np.array([])
v = np.concatenate((u,y))
v

array([0., 1., 2., 3.])

In [ ]:
u = np.array([])
u

array([], dtype=float64)